apiVersion: v1
kind: Pod
metadata:
  name: mas-fuel
  labels:
    k8s-app: gis-pyspark
spec:
  containers:
  - name: gis-pyspark-devel
    image: sdsc/gis-pyspark:latest
    imagePullPolicy: Always
    # args: ["sleep", "36500000"]
    args: ["python", "/usr/local/bin/jupyter-notebook", "--ip=*", "--port=8888", "--allow-root", "--NotebookApp.iopub_data_rate_limit=2147483647"]
    resources:
      limits:
        memory: "8G"
        cpu: 4
      requests:
        memory: "8G"
        cpu: 4
  restartPolicy: Never
---
kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: gis-pyspark
  name: gis-pyspark
  namespace: ucsd-edu
spec:
  type: NodePort
  ports:
  - port: 8888
    name: web
  selector:
    k8s-app: gis-pyspark
